# Site settings
baseurl = "https://aaronmast.dev/"
# themesDir = "../.."
languageCode = "en-us"
title = "Aaron's Blog"
theme = "hugo-cactus-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-101594460-1"
# Disable comments by leaving disqusShortname empty
disqusShortname = ""

[params]
	name = "Aaron Mast"
	description = "A place for random musings."
	bio = "A Software Developer living in Charleston SC"
	# Enter optionally your twitter account
	twitter = "amast09"
	enableRSS = false

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = ['css/prism.css', 'css/custom.css']
	customJS  = ['js/prism.js']

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = " home"
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = " "
	# Sharing options and author information in posts
	aboutAuthor = "I write code."
	tweet = ""
	share = ""
	# 404 page
	title404 = "Page not found"
	subtitle404 = "The page you are looking for does not exist."

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = ""

# Add additional social link entries underneath
[social]
    twitter  = "https://twitter.com/amast09"
    github   = "https://www.github.com/amast09"
