baseurl = "https://aaronmast.dev/"
languageCode = "en-us"
defaultContentLanguage = "en"
enableEmoji = true
title = "Aaron's Site"
theme = "gokarna"
pygmentsStyle = "monokai"


[params]
	name = "Aaron Mast"
	description = "A Remote Software Engineer"
	avatarURL = "/images/profile-picture.webp"
	enableRSS = false
  customHeadHTML = """
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-7Y1RNHVW6C"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-7Y1RNHVW6C');
    </script>
    <style>
      .footer { display: none }
    </style>
  """

[menu]
	[[menu.main]]
    # Unique identifier for a menu item
    identifier = "about"

    url = "/about/"
    
    # You can add extra information before the name (HTML format is supported), such as icons
    pre = "<span data-feather='user'></span>"

    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""

    # Display name
    name = "About"

    # Weights are used to determine the ordering
    weight = 1

  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "posts"

    url = "/blog/"
    
    # You can add extra information before the name (HTML format is supported), such as icons
    pre = "<span data-feather='book'></span>"

    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""

    # Display name
    name = "Posts"

    # Weights are used to determine the ordering
    weight = 2

  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "projects"

    url = "/projects/"
    
    # You can add extra information before the name (HTML format is supported), such as icons
    pre = "<span data-feather='code'></span>"

    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""

    # Display name
    name = "Projects"

    # Weights are used to determine the ordering
    weight = 3
    
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/amast09"
    weight = 4
    
    name = "Github"

    # We use feather-icons: https://feathericons.com/
    pre = "<span data-feather='github'></span>"

  [[menu.main]]
    identifier = "linkedin"
    url = "https://linkedin.com/in/aaronamast"
    weight = 4
    
    name = "LinkedIn"

    # We use feather-icons: https://feathericons.com/
    pre = "<span data-feather='linkedin'></span>"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true